name: "DevOps Service Request (Global)"
description: "Submit a request for infrastructure, access, or deployment support."
title: "[DevOps]: "
labels: ["type: deployment"]
projects: ["datavisyn/10", "datavisyn/74"]
assignees: ["dvvanessastoiber"]
type: Deployment
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this deployment issue!
  - type: dropdown
    id: stage
    attributes:
      label: Stage
      description: Which stage is affected or relevant?
      options:
        - Playground
        - Develop
        - DEV
        - QA
        - UAT
        - ENG
        - VER
        - EXE
        - Production
      multiple: true
    validations:
      required: true
  - type: textarea
    id: main-description
    attributes:
      label: Description
      description: Clear description of the infrastructure change or support needed. Please make sure to share secret values only through Bitwarden Send.
  - type: checkboxes
    id: impact-risks
    attributes:
      label: Impact and Risks
      options:
        - label: This change requires a maintenance window.
          required: false
        - label: This change affects production traffic.
          required: false
        - label: This involves sensitive data or secrets
          required: false
  - type: textarea
    id: time-frame
    attributes:
      label: Time Frame
      description: If applicable, please state in which timeframe the changes should be applied (e.g., before 2PM).        
  - type: textarea
    id: slack
    attributes:
      label: Slack channel
      description: Please let us know which Slack channel should be used for further communication and updates.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### ⚠️ **Action Required: Select Category**
        Before submitting, please look at the additional options at the bottom of this frame and select the appropriate option in the `Category` dropdown. This ensures your request is routed to the correct DevOps queue and meets our defined SLAs. If `C3 - Critical` is selected, please escalate via the deployment Slack channel (for production outage) or act according to the Incident Management Policy (for security incidents).